name: Assignment CI

on:
  push:
    branches:
      - '*'

jobs:
  full-test:
    runs-on: self-hosted
    container:
      image: cuaesd/aesd-autotest:24-assignment4-buildroot
      options: -v /etc/ssl/certs:/etc/ssl/certs:ro

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_K }}

      - name: Disable SSL Certificate Checks
        run: |
          echo "check_certificate = off" >> ~/.wgetrc
          echo "insecure" >> ~/.curlrc
          echo "BR2_WGET_OPTS=--no-check-certificate" >> $GITHUB_ENV

      - name: Run full test
        run: ./full-test.sh
